artindex = {
    "background" : { "path": "../bg-battle.png", "frame_height": 1024, "named_frames": {} },
    "background_char" : { "path": "../bg_characterselect.png", "frame_height": 1024, "named_frames": {} },
    "logo_deathmath_nobuttons" : { "path": "../logo_deathmath_nobuttons.png", "frame_height": 1024, "named_frames": {} },
    "newton" : { "path": "../newton_fight.png", "frame_height": 264, "named_frames": {} },
    "archimedes" : { "path": "../archimedes_fight.png", "frame_height": 263, "named_frames": {} },
    "einstein" : { "path": "../einstein_fight.png", "frame_height": 250, "named_frames": {} },
    "button_add" : { "path": "../button_add.png", "frame_height": 140, "named_frames": {} },
    "button_subtract" : { "path": "../button_subtract.png", "frame_height": 140, "named_frames": {} },
    "button_divide" : { "path": "../button_divide.png", "frame_height": 140, "named_frames": {} },
    "button_multiply" : { "path": "../button_multiply.png", "frame_height": 140, "named_frames": {} },
    "button_add_press" : { "path": "../button_add_press.png", "frame_height": 140, "named_frames": {} },
    "button_subtract_press" : { "path": "../button_subtract_press.png", "frame_height": 140, "named_frames": {} },
    "button_divide_press" : { "path": "../button_divide_press.png", "frame_height": 140, "named_frames": {} },
    "button_multiply_press" : { "path": "../button_multiply_press.png", "frame_height": 140, "named_frames": {} },
    "bg_health_empty" : { "path": "../bg_health_empty.png", "frame_height": 140, "named_frames": {} },
    "bg_health_full_red" : { "path": "../bg_health_full_red.png", "frame_height": 140, "named_frames": {} },
    "bg_health_full_blue" : { "path": "../bg_health_full_blue.png", "frame_height": 140, "named_frames": {} },
}
